openapi: 3.0.0
info:
  title: ga4gh/read_service.proto
  version: version not set
paths:
  /reads/search:
    post:
      summary: Gets a list of `ReadAlignment` s for one or more `ReadGroup` s.
      description: >-
        `searchReads` operates over a genomic coordinate space of reference
        sequence

        and position defined by the `Reference` s to which the requested
        `ReadGroup` s are

        aligned.


        If a target positional range is specified, search returns all reads
        whose

        alignment to the reference genome *overlap* the range. A query which
        specifies

        only read group IDs yields all reads in those read groups, including
        unmapped

        reads.


        All reads returned (including reads on subsequent pages) are ordered by
        genomic

        coordinate (by reference sequence, then position). Reads with equivalent
        genomic

        coordinates are returned in an unspecified order. This order must be
        consistent

        for a given repository, such that two queries for the same content
        (regardless

        of page size) yield reads in the same order across their respective
        streams of

        paginated responses.


        `POST /reads/search` must accept a JSON version of `SearchReadsRequest`
        as

        the post body and will return a JSON version of `SearchReadsResponse`.
      operationId: SearchReads
      responses:
        '200':
          description: A successful response.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SearchReadsResponse'
      tags:
        - GA4GH
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SearchReadsRequest'
        required: true