components:
  schemas:
    GetInfoResponse:
      description: This is the response from `GET /info`.
      properties:
        attributes:
          $ref: '#/components/schemas/Attributes'
        protocol_version:
          description: |-
            The string of the protocol version offered by the service. For
            example, "0.6.0a10".
          type: string
      type: object
info:
  title: BrAPI
  version: ''
openapi: 3.0.0
paths: {}
