components:
  schemas:
    HGVSAnnotation:
      description: |-
        A HGVSAnnotation record holds Human Genome Variation Society descriptions of
        the sequence change with respect to genomic, transcript and protein
        sequences. See: http:// www.hgvs.org/mutnomen/recs.html.
        Descriptions should be provided at genomic level
         - Descriptions at transcript level should be provided when the allele
           lies within a transcript
         - Descriptions at protein level should be provided when the allele
           lies within the translated sequence or stop codon.
      properties:
        genomic:
          type: string
        protein:
          type: string
        transcript:
          type: string
      type: object
info:
  title: BrAPI
  version: ''
openapi: 3.0.0
paths: {}
