components:
  schemas:
    SearchVariantAnnotationsRequest:
      description: This request maps to the body of `POST /variantannotations/search` as JSON.
      properties:
        effects:
          description: |-
            This filter allows variant, transcript combinations to be extracted by
            effect type(s). Only return variant annotations including any of these
            effects and only return transcript effects including any of these
            effects. Exact matching across all fields of the Sequence Ontology
            OntologyTerm is required. (A transcript effect may have multiple SO
            effects which will all be reported.) If empty, return all variant
            annotations.
          items:
            $ref: '#/components/schemas/OntologyTerm'
          type: array
        end:
          description: |-
            Required if reference_name or reference_id supplied. The end of the window
            (0-based, exclusive) for which variants with overlapping reference
            alleles should be returned.
          format: int64
          type: string
        page_size:
          description: |-
            Specifies the maximum number of results to return in a single page. If
            unspecified, a system default will be used.
          format: int32
          type: integer
        page_token:
          description: |-
            The continuation token, which is used to page through large result sets.
            To get the next page of results, set this parameter to the value of
            `next_page_token` from the previous response.
          type: string
        reference_id:
          description: |-
            Only return variants with reference alleles on the reference with this
            ID. One of this field or `reference_name` is required.
          type: string
        reference_name:
          description: |-
            Only return variants with reference alleles on the reference with this
            name. One of this field or `reference_id` is required.
          type: string
        start:
          description: |-
            Required if reference_name or reference_id supplied. The beginning of the
            window (0-based, inclusive) for which variants with overlapping reference
            alleles should be returned. Genomic positions are non-negative integers
            less than reference length. Requests spanning the join of circular
            genomes are represented as two requests one on each side of the join
            (position 0).
          format: int64
          type: string
        variant_annotation_set_id:
          description: Required. The ID of the variant annotation set to search over.
          type: string
      type: object
info:
  title: BrAPI
  version: ''
openapi: 3.0.0
paths: {}
