components:
  schemas:
    SearchVariantAnnotationSetsRequest:
      description: |-
        This request maps to the body of `POST /variantannotationsets/search` as
        JSON.
      properties:
        page_size:
          description: |-
            Specifies the maximum number of results to return in a single page. If
            unspecified, a system default will be used.
          format: int32
          type: integer
        page_token:
          description: |-
            The continuation token, which is used to page through large result sets.
            To get the next page of results, set this parameter to the value of
            `next_page_token` from the previous response.
          type: string
        variant_set_id:
          description: Required. The `VariantSet` to search.
          type: string
      type: object
info:
  title: BrAPI
  version: ''
openapi: 3.0.0
paths: {}
