components:
  schemas:
    VariantAnnotationSet:
      description: |-
        A VariantAnnotationSet record groups VariantAnnotation records. It is derived
        from a VariantSet and holds information describing the software and reference
        data used in the annotation.
      properties:
        analysis:
          $ref: '#/components/schemas/Analysis'
        attributes:
          $ref: '#/components/schemas/Attributes'
        id:
          title: The ID of the variant annotation set record
          type: string
        name:
          description: The variant annotation set name.
          type: string
        variant_set_id:
          title: The ID of the variant set to which this annotation set belongs
          type: string
      type: object
info:
  title: BrAPI
  version: ''
openapi: 3.0.0
paths: {}
