components:
  schemas:
    RnaQuantificationSet:
      description: |-
        A collection of associated RNAQuantifications.  Typically this will be all
        the Quantifications of samples from an experiment.  For example, a time
        course experiment would be described by a RnaQuantificationSet with the
        individual RNASeq experiments of the time point being represented as the
        member RnaQuantifications.
      properties:
        attributes:
          $ref: '#/components/schemas/Attributes'
        dataset_id:
          description: The ID of the dataset this RNA Quantification set belongs to.
          type: string
        id:
          description: The RNA quantification set ID.
          type: string
        name:
          description: The RNA quantification set name.
          type: string
      type: object
info:
  title: BrAPI
  version: ''
openapi: 3.0.0
paths: {}
