components:
  schemas:
    SearchRnaQuantificationsRequest:
      description: |-
        This request maps to the body of 'POST /rnaquantifications/search'
        as JSON.
      properties:
        biosample_id:
          description: Return only RNA quantifications regarding the specified biosample. Optional.
          type: string
        page_size:
          description: |-
            Specifies the maximum number of results to return in a single page.
            If unspecified, a system default will be used.
          format: int32
          type: integer
        page_token:
          description: |-
            The continuation token, which is used to page through large result sets.
            To get the next page of results, set this parameter to the value of
            'nextPageToken' from the previous response.
          type: string
        rna_quantification_set_id:
          description: |-
            Return only Rna Quantifications which belong to this set.
            Must be specified.
          type: string
      type: object
info:
  title: BrAPI
  version: ''
openapi: 3.0.0
paths: {}
