components:
  schemas:
    SearchExpressionLevelsRequest:
      description: |-
        ****************  /expressionlevels/search  *******************
        This request maps to the body of 'POST /expressionlevels/search'
        as JSON.
      properties:
        names:
          description: Only return expressions with any of the names (strict string matching).
          items:
            type: string
          type: array
        page_size:
          description: |-
            Specifies the maximum number of results to return in a single page.
            If unspecified, a system default will be used.
          format: int32
          type: integer
        page_token:
          description: |-
            The continuation token, which is used to page through large result sets.
            To get the next page of results, set this parameter to the value of
            'nextPageToken' from the previous response.
          type: string
        rna_quantification_id:
          description: The rnaQuantification to restrict search to.
          type: string
        threshold:
          format: float
          title: |-
            Only return ExpressionLevel records with expressions exceeding
            this value.  (Defaults to 0.0)
          type: number
      type: object
info:
  title: BrAPI
  version: ''
openapi: 3.0.0
paths: {}
