components:
  schemas:
    LinearAlignment:
      description: |-
        A linear alignment describes the alignment of a read to a Reference, using a
        position and CIGAR array.
      properties:
        cigar:
          description: |-
            Represents the local alignment of this sequence (alignment matches, indels,
            etc)
            versus the reference.
          items:
            $ref: '#/components/schemas/CigarUnit'
          type: array
        mapping_quality:
          description: |-
            The mapping quality of this alignment, meaning the likelihood that the read
            maps to this position.

            Specifically, this is -10 log10 Pr(mapping position is wrong), rounded to
            the nearest integer.
          format: int32
          type: integer
        position:
          $ref: '#/components/schemas/Position'
      type: object
info:
  title: BrAPI
  version: ''
openapi: 3.0.0
paths: {}
