components:
  schemas:
    Position:
      description: |-
        A `Position` is an unoriented base in some `Reference`. A `Position` is
        represented by a `Reference` name, and a base number on that `Reference`
        (0-based).
      properties:
        position:
          description: |-
            The 0-based offset from the start of the forward strand for that
            `Reference`. Genomic positions are non-negative integers less than
            `Reference` length.
          format: int64
          type: string
        reference_name:
          description: The name of the `Reference` on which the `Position` is located.
          type: string
        strand:
          $ref: '#/components/schemas/Strand'
      type: object
info:
  title: BrAPI
  version: ''
openapi: 3.0.0
paths: {}
