components:
  schemas:
    ReadAlignment:
      description: |-
        Each read alignment describes an alignment with additional information
        about the fragment and the read. A read alignment object is equivalent to a
        line in a SAM file.
      properties:
        aligned_quality:
          description: |-
            The quality of the read sequence contained in this alignment message
            (equivalent to QUAL in SAM).

            `alignedSequence` and `alignedQuality` may be shorter than the full read
            sequence and quality. This will occur if the alignment is part of a
            chimeric alignment, or if the read was trimmed. When this occurs, the CIGAR
            for this read will begin/end with a hard clip operator that will indicate
            the length of the excised sequence.
          items:
            format: int32
            type: integer
          type: array
        aligned_sequence:
          description: |-
            The bases of the read sequence contained in this alignment record
            (equivalent to SEQ in SAM).

            `alignedSequence` and `alignedQuality` may be shorter than the full read
            sequence and quality. This will occur if the alignment is part of a
            chimeric alignment, or if the read was trimmed. When this occurs, the CIGAR
            for this read will begin/end with a hard clip operator that will indicate
            the length of the excised sequence.
          type: string
        alignment:
          $ref: '#/components/schemas/LinearAlignment'
        attributes:
          $ref: '#/components/schemas/Attributes'
        duplicate_fragment:
          description: The fragment is a PCR or optical duplicate (SAM flag 0x400).
          format: boolean
          type: boolean
        failed_vendor_quality_checks:
          description: The read fails platform or vendor quality checks (SAM flag 0x200).
          format: boolean
          type: boolean
        fragment_length:
          description: The observed length of the fragment, equivalent to TLEN in SAM.
          format: int32
          type: integer
        fragment_name:
          description: The fragment name. Equivalent to QNAME (query template name) in SAM.
          type: string
        id:
          description: |-
            The read alignment ID. This ID is unique within the read group this
            alignment belongs to.

            For performance reasons, this field may be omitted by a backend.
            If provided, its intended use is to make caching and UI display easier for
            genome browsers and other lightweight clients.
          type: string
        improper_placement:
          description: |-
            The orientation and the distance between reads from the fragment are
            inconsistent with the sequencing protocol (inverse of SAM flag 0x2).
          format: boolean
          type: boolean
        next_mate_position:
          $ref: '#/components/schemas/Position'
        number_reads:
          description: The number of reads in the fragment (extension to SAM flag 0x1).
          format: int32
          type: integer
        read_group_id:
          title: |-
            The ID of the read group this read belongs to.
            (Every read must belong to exactly one read group.)
          type: string
        read_number:
          description: |-
            The read ordinal in the fragment, 0-based and less than numberReads. This
            field replaces SAM flag 0x40 and 0x80 and is intended to more cleanly
            represent multiple reads per fragment.
          format: int32
          type: integer
        secondary_alignment:
          description: |-
            Whether this alignment is secondary. Equivalent to SAM flag 0x100.
            A secondary alignment represents an alternative to the primary alignment
            for this read. Aligners may return secondary alignments if a read can map
            ambiguously to multiple coordinates in the genome.

            By convention, each read has one and only one alignment where both
            secondaryAlignment and supplementaryAlignment are false.
          format: boolean
          type: boolean
        supplementary_alignment:
          description: |-
            Whether this alignment is supplementary. Equivalent to SAM flag 0x800.
            Supplementary alignments are used in the representation of a chimeric
            alignment. In a chimeric alignment, a read is split into multiple
            linear alignments that map to different reference contigs. The first
            linear alignment in the read will be designated as the representative
            alignment; the remaining linear alignments will be designated as
            supplementary alignments. These alignments may have different mapping
            quality scores.

            In each linear alignment in a chimeric alignment, the read will be hard
            clipped. The `alignedSequence` and `alignedQuality` fields in the alignment
            message will only represent the bases for its respective linear alignment.
          format: boolean
          type: boolean
      type: object
info:
  title: BrAPI
  version: ''
openapi: 3.0.0
paths: {}
