components:
  schemas:
    ReadGroupSet:
      description: |-
        A ReadGroupSet is a logical collection of ReadGroups. Typically one
        ReadGroupSet represents all the reads from one experimental sample.
      properties:
        attributes:
          $ref: '#/components/schemas/Attributes'
        dataset_id:
          description: The ID of the dataset this read group set belongs to.
          type: string
        id:
          description: The read group set ID.
          type: string
        name:
          description: The read group set name.
          type: string
        read_groups:
          items:
            $ref: '#/components/schemas/ReadGroup'
          type: array
        stats:
          $ref: '#/components/schemas/ReadStats'
      type: object
info:
  title: BrAPI
  version: ''
openapi: 3.0.0
paths: {}
