components:
  schemas:
    SearchReadGroupSetsRequest:
      description: |-
        This request maps to the body of `POST /readgroupsets/search` as JSON.

        TODO: Factor this out to a common API patterns section.
        - If searching by a resource ID, and that resource is not found, the method
          will return a `404` HTTP status code (`NOT_FOUND`).
        - If searching by other attributes, e.g. `name`, and no matches are found, the
          method will return a `200` HTTP status code (`OK`) with an empty result list.
      properties:
        biosample_id:
          description: |-
            Specifying the id of a Biosample record will return only readgroups
             with the given biosampleId.
          type: string
        dataset_id:
          description: The dataset to search.
          type: string
        name:
          description: Only return read group sets with this name (case-sensitive, exact match).
          type: string
        page_size:
          description: |-
            Specifies the maximum number of results to return in a single page.
            If unspecified, a system default will be used.
          format: int32
          type: integer
        page_token:
          description: |-
            The continuation token, which is used to page through large result sets.
            To get the next page of results, set this parameter to the value of
            `next_page_token` from the previous response.
          type: string
      type: object
info:
  title: BrAPI
  version: ''
openapi: 3.0.0
paths: {}
