components:
  schemas:
    CigarUnit:
      description: A single CIGAR operation.
      properties:
        operation:
          $ref: '#/components/schemas/CigarUnitOperation'
        operation_length:
          description: The number of genomic bases that the operation runs for. Required.
          format: int64
          type: string
        reference_sequence:
          description: |-
            `referenceSequence` is only used at mismatches
            (`SEQUENCE_MISMATCH`) and deletions (`DELETE`).
            Filling this field replaces SAM's MD tag. If the relevant information is
            not available, this field is unset.
          type: string
      type: object
info:
  title: BrAPI
  version: ''
openapi: 3.0.0
paths: {}
