components:
  schemas:
    SearchReadsRequest:
      description: |-
        ******************  /reads  *********************
        This request maps to the body of `POST /reads/search` as JSON.

        If a reference is specified, all queried `ReadGroup`s must be aligned
        to `ReferenceSet`s containing that same `Reference`. If no reference is
        specified, all `ReadGroup`s must be aligned to the same `ReferenceSet`.
      properties:
        end:
          description: |-
            The end position (0-based, exclusive) of this query.
            If a reference is specified, this defaults to the
            reference's length.
          format: int64
          type: string
        page_size:
          description: |-
            Specifies the maximum number of results to return in a single page.
            If unspecified, a system default will be used.
          format: int32
          type: integer
        page_token:
          description: |-
            The continuation token, which is used to page through large result sets.
            To get the next page of results, set this parameter to the value of
            `next_page_token` from the previous response.
          type: string
        read_group_ids:
          description: The ReadGroups to search. At least one id must be specified.
          items:
            type: string
          type: array
        reference_id:
          description: |-
            The reference to query. Leaving blank returns results from all
            references, including unmapped reads - this could be very large.
          type: string
        start:
          description: |-
            The start position (0-based) of this query.
            If a reference is specified, this defaults to 0.
            Genomic positions are non-negative integers less than reference length.
            Requests spanning the join of circular genomes are represented as
            two requests one on each side of the join (position 0).
          format: int64
          type: string
      type: object
info:
  title: BrAPI
  version: ''
openapi: 3.0.0
paths: {}
