openapi: 3.0.0
info:
  title: ga4gh/metadata_service.proto
  version: version not set
paths:
  /datasets/search:
    post:
      summary: Gets a list of `Dataset` matching the search criteria.
      description: |-
        `POST /datasets/search` must accept a JSON version of
        `SearchDatasetsRequest` as the post body and will return a JSON
        version of `SearchDatasetsResponse`.
      operationId: SearchDatasets
      responses:
        '200':
          description: A successful response.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SearchDatasetsResponse'
      tags:
        - GA4GH
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SearchDatasetsRequest'
        required: true