components:
  schemas:
    EnvironmentalContext:
      description: |-
        The context in which a genotype gives rise to a phenotype.
        This is fairly open-ended; as a stub we have a simple ontology term.
        For example, a controlled term for a drug, or perhaps an instance of a
        complex environment including temperature and air quality, or perhaps
        the anatomical environment (gut vs tissue type vs whole organism).
      properties:
        description:
          title: |-
            A textual description of the environment. This is used to complement
            the structured description in the environmentType field
          type: string
        environment_type:
          $ref: '#/components/schemas/OntologyTerm'
        id:
          description: The Environment ID.
          type: string
      type: object
info:
  title: BrAPI
  version: ''
openapi: 3.0.0
paths: {}
