components:
  schemas:
    EvidenceQuery:
      description: Evidence for the phenotype association.
      properties:
        description:
          title: The system may support regex. https://www.w3.org/TR/xpath-functions/#regex-syntax
          type: string
        evidenceType:
          $ref: '#/components/schemas/OntologyTerm'
        external_identifiers:
          items:
            $ref: '#/components/schemas/ExternalIdentifier'
          title: Only match Evidence messages that have any of these external identifiers
          type: array
      type: object
info:
  title: BrAPI
  version: ''
openapi: 3.0.0
paths: {}
