components:
  schemas:
    Evidence:
      description: |-
        Evidence for the phenotype association.
        This is also a stub for further expansion.  We should consider moving this into
        it's own schema.
      properties:
        description:
          title: |-
            A textual description of the evidence. This is used to complement the
            structured description in the evidence_type field
          type: string
        evidence_type:
          $ref: '#/components/schemas/OntologyTerm'
        info:
          additionalProperties:
            $ref: '#/components/schemas/ListValue'
          description: Additional annotation data in key-value pairs.
          type: object
      type: object
info:
  title: BrAPI
  version: ''
openapi: 3.0.0
paths: {}
