components:
  schemas:
    PhenotypeAssociationSet:
      description: The top level container for phenotype association data.
      properties:
        dataset_id:
          description: The ID of the dataset this phenotype association set belongs to.
          type: string
        id:
          description: The phenotype association set ID.
          type: string
        info:
          additionalProperties:
            $ref: '#/components/schemas/ListValue'
          description: Optional additional information for this phenotype association set.
          type: object
        name:
          description: The phenotype association set name.
          type: string
      type: object
info:
  title: BrAPI
  version: ''
openapi: 3.0.0
paths: {}
