components:
  schemas:
    PhenotypeInstance:
      properties:
        age_of_onset:
          $ref: '#/components/schemas/OntologyTerm'
        description:
          description: |-
            A textual description of the phenotype. This is used to complement the
            structured phenotype description in the type field.
          type: string
        id:
          description: The Phenotype ID.
          type: string
        info:
          additionalProperties:
            $ref: '#/components/schemas/ListValue'
          description: Additional annotation data in key-value pairs.
          type: object
        qualifier:
          items:
            $ref: '#/components/schemas/OntologyTerm'
          title: |-
            PATO is recommended.  Often this qualifier might be for abnormal/normal,
            or severity.
            For example, severe: http://purl.obolibrary.org/obo/PATO_0000396
            or abnormal: http://purl.obolibrary.org/obo/PATO_0000460
          type: array
        type:
          $ref: '#/components/schemas/OntologyTerm'
      title: |-
        An association to a phenotype and related information.
        This record is intended primarily to be used in conjunction with variants, but
        the record can also be composed with other kinds of entities such as diseases
      type: object
info:
  title: BrAPI
  version: ''
openapi: 3.0.0
paths: {}
