components:
  schemas:
    SearchPhenotypeAssociationSetsRequest:
      description: This request maps to the body of `POST /phenotypeassociationsets/search` as JSON.
      properties:
        dataset_id:
          title: The `Dataset` to search. Mandatory
          type: string
        page_size:
          description: |-
            Specifies the maximum number of results to return in a single page.
            If unspecified, a system default will be used.
          format: int64
          type: string
        page_token:
          description: |-
            The continuation token, which is used to page through large result sets.
            To get the next page of results, set this parameter to the value of
            `nextPageToken` from the previous response.
          type: string
      type: object
info:
  title: BrAPI
  version: ''
openapi: 3.0.0
paths: {}
