components:
  schemas:
    SearchPhenotypesRequest:
      properties:
        age_of_onset:
          $ref: '#/components/schemas/OntologyTerm'
        description:
          title: The system may support regex. https://www.w3.org/TR/xpath-functions/#regex-syntax
          type: string
        id:
          title: |-
            Phenotype ID
            TODO remove if a get-by-phenotype ID endpoint is added
          type: string
        page_size:
          description: |-
            Specifies the maximum number of results to return in a single page.
            If unspecified, a system default will be used.
          format: int64
          type: string
        page_token:
          description: |-
            The continuation token, which is used to page through large result sets.
            To get the next page of results, set this parameter to the value of
            `next_page_token` from the previous response.
          type: string
        phenotype_association_set_id:
          title: The `PhenotypeAssociationSet` to search. Mandatory
          type: string
        qualifiers:
          items:
            $ref: '#/components/schemas/OntologyTerm'
          title: terms should be OR'd together. e.g. (severe OR abnormal)
          type: array
        type:
          $ref: '#/components/schemas/OntologyTerm'
      type: object
info:
  title: BrAPI
  version: ''
openapi: 3.0.0
paths: {}
