components:
  schemas:
    study:
      properties:
        active:
          description: Is this study currently active
          type: boolean
        additionalInfo:
          additionalProperties:
            type: string
          description: Additional arbitrary info
          type: object
        commonCropName:
          description: Common name for the crop associated with this study
          type: string
        contacts:
          description: List of contact entities associated with this study
          items:
            $ref: '#/components/schemas/contact'
          type: array
        dataLinks:
          description: List of links to extra data files associated with this study. Extra data could include notes, images, and reference data.
          items:
            $ref: '#/components/schemas/dataLink'
          type: array
        documentationURL:
          description: A URL to the human readable documentation of this object
          format: uri
          type: string
        endDate:
          description: The date the study ends
          format: date
          type: string
        lastUpdate:
          description: The date and time when this study was last modified
          properties:
            timestamp:
              format: date-time
              type: string
            version:
              type: string
          type: object
        license:
          description: The usage license associated with the study data
          type: string
        location:
          $ref: '#/components/schemas/location'
        seasons:
          description: List of seasons over which this study was performed.
          items:
            type: string
          type: array
        startDate:
          description: The date this study started
          format: date
          type: string
        studyDbId:
          description: The ID which uniquely identifies a study within the given database server
          type: string
        studyDescription:
          description: The description of this study
          type: string
        studyName:
          description: The human readable name for a study
          type: string
        studyType:
          deprecated: true
          description: DEPRECATED in v1.3 - See "studyTypeName"
          type: string
        studyTypeDbId:
          description: The unique identifier of the type of study being performed.
          type: string
        studyTypeName:
          description: The name of the type of study being performed. ex. "Yield Trial", etc
          type: string
        trialDbId:
          description: The ID which uniquely identifies a trial
          type: string
        trialName:
          description: The human readable name of a trial
          type: string
      type: object
info:
  title: BrAPI
  version: ''
openapi: 3.0.0
paths: {}
