openapi: 3.0.0
info:
  title: ga4gh/peer_service.proto
  version: version not set
paths:
  /announce:
    post:
      summary: |-
        Allows a client to notify a service of a potential peer.
        Services are expected to log these requests and implement
        policies for adding peers to their peer lists as desired.
      description: |-
        The AnnouncePeerResponse only notifies the requester whether
        the request was valid. To find if their announce request
        has been accepted they must make a `ListPeersRequest`.
        `POST /peers/announce` must accept a JSON version of
        `AnnouncePeerRequest` as the post body and will return a JSON
        version of `AnnouncePeerResponse`.
      operationId: AnnouncePeer
      responses:
        '200':
          description: A successful response.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AnnouncePeerResponse'
      tags:
        - GA4GH