openapi: 3.0.0
info:
  title: ga4gh/peer_service.proto
  version: version not set
paths:
  /info:
    get:
      summary: |-
        Provides peers with a way to identify the protocol version
        of a peer. Other information describing the service can
        be included in the `info` field of the `GetInfoResponse`.
      description: |-
        `GET /info` will return a JSON version of `GetInfoResponse`.
        and does not require any parameters.
      operationId: Info
      responses:
        '200':
          description: A successful response.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GetInfoResponse'
      tags:
        - GA4GH