components:
  schemas:
    SearchVariantsResponse:
      description: This is the response from `POST /variants/search` expressed as JSON.
      properties:
        next_page_token:
          description: |-
            The continuation token, which is used to page through large result sets.
            Provide this value in a subsequent request to return the next page of
            results. This field will be empty if there aren't any additional results.
          type: string
        variants:
          description: |-
            The list of matching variants.
            If the `callSetId` field on the returned calls is not present,
            the ordering of the call sets from a `SearchCallSetsRequest`
            over the parent `VariantSet` is guaranteed to match the ordering
            of the calls on each `Variant`. The number of results will also be
            the same.
          items:
            $ref: '#/components/schemas/Variant'
          type: array
      type: object
info:
  title: BrAPI
  version: ''
openapi: 3.0.0
paths: {}
