components:
  schemas:
    Value:
      description: |-
        `Value` represents a dynamically typed value which can be either
        null, a number, a string, a boolean, a recursive struct value, or a
        list of values. A producer of value is expected to set one of that
        variants, absence of any variant indicates an error.

        The JSON representation for `Value` is JSON value.
      properties:
        bool_value:
          description: Represents a boolean value.
          format: boolean
          type: boolean
        list_value:
          $ref: '#/components/schemas/ListValue'
        null_value:
          $ref: '#/components/schemas/NullValue'
        number_value:
          description: Represents a double value.
          format: double
          type: number
        string_value:
          description: Represents a string value.
          type: string
        struct_value:
          $ref: '#/components/schemas/Struct'
      type: object
info:
  title: BrAPI
  version: ''
openapi: 3.0.0
paths: {}
