components:
  schemas:
    VariantSet:
      description: |-
        A VariantSet is a collection of variants and variant calls intended to be
        analyzed together.
      properties:
        dataset_id:
          description: The ID of the dataset this variant set belongs to.
          type: string
        id:
          description: The variant set ID.
          type: string
        metadata:
          description: |-
            Optional metadata associated with this variant set.
            This array can be used to store information about the variant set, such as
            information found in VCF header fields, that isn't already available in
            first class fields such as "name".
          items:
            $ref: '#/components/schemas/VariantSetMetadata'
          type: array
        name:
          description: The variant set name.
          type: string
        reference_set_id:
          description: |-
            The ID of the reference set that describes the sequences used by the
            variants in this set.
          type: string
      type: object
info:
  title: BrAPI
  version: ''
openapi: 3.0.0
paths: {}
