openapi: 3.0.0
info:
  title: ga4gh/reference_service.proto
  version: version not set
paths:
  /references/{referenceDbId}:
    get:
      summary: Gets a `Reference` by ID.
      description: |-
        `GET /references/{reference_id}` will return a JSON version of
        `Reference`.
      operationId: GetReference
      parameters:
        - name: referenceDbId
          description: The ID of the `Reference` to be retrieved.
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: A successful response.
          content:
            application/json:
              schema:
                properties:
                  metadata:
                    $ref: '#/components/schemas/metadata'
                  result:
                    $ref: '#/components/schemas/Reference'
                required:
                - metadata
                - result
                title: ReferenceResponse
                type: object
          headers: {}
        '400':
          $ref: '#/components/responses/400BadRequest'
        '401':
          $ref: '#/components/responses/401Unauthorized'
        '403':
          $ref: '#/components/responses/403Forbidden'
        '404':
          $ref: '#/components/responses/404NotFound'
      tags:
        - GA4GH