openapi: 3.0.0
info:
  title: ga4gh/reference_service.proto
  version: version not set
paths:
  /search/referencesets/{searchResultsDbId}: 
    get:
      summary: Gets a list of `ReferenceSet` matching the search criteria.
      description: |-
        `POST /referencesets/search` must accept a JSON version of
        `SearchReferenceSetsRequest` as the post body and will return a JSON
        version of `SearchReferenceSetsResponse`.
      operationId: SearchReferenceSets
      parameters:
      - $ref: '#/components/parameters/searchResultsDbId'
      - $ref: '#/components/parameters/page'
      - $ref: '#/components/parameters/pageSize'
      - $ref: '#/components/parameters/authorizationHeader'
      responses:
        '200':
          description: A successful response.
          content:
            application/json:
              schema:
                properties:
                  metadata:
                    $ref: '#/components/schemas/metadata'
                  result:
                    properties:
                      data:
                        items:
                          $ref: '#/components/schemas/ReferenceSet'
                        type: array
                    required:
                    - data
                    title: referenceListResponseResult
                    type: object
                required:
                - metadata
                - result
                title: referenceListResponse
                type: object
          headers: {}
        '400':
          $ref: '#/components/responses/400BadRequest'
        '401':
          $ref: '#/components/responses/401Unauthorized'
        '403':
          $ref: '#/components/responses/403Forbidden'
      tags:
        - GA4GH