openapi: 3.0.0
info:
  title: ga4gh/sequence_annotation_service.proto
  version: version not set
paths:
  /continuoussets/search:
    post:
      summary: Gets a list of `ContinuousSet` matching the search criteria.
      description: |-
        `POST /continuoussets/search` must accept a JSON version of
        `SearchContinuousSetsRequest` as the post body and will return a JSON
        version of `SearchContinuousSetsResponse`.
      operationId: SearchContinuousSets
      responses:
        '200':
          description: A successful response.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SearchContinuousSetsResponse'
      tags:
        - GA4GH
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SearchContinuousSetsRequest'
        required: true