openapi: 3.0.0
info:
  title: ga4gh/sequence_annotation_service.proto
  version: version not set
paths:
  /continuous/search:
    post:
      summary: Gets continuous values matching the search criteria.
      description: >-
        `POST /continuous/search` must accept a JSON version of

        `SearchContinuousRequest` as the post body and will return a JSON
        version

        of `SearchContinuousResponse`.
      operationId: SearchContinuous
      responses:
        '200':
          description: A successful response.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SearchContinuousResponse'
      tags:
        - GA4GH
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SearchContinuousRequest'
        required: true