openapi: 3.0.0
info:
  title: ga4gh/sequence_annotation_service.proto
  version: version not set
paths:
  /featuresets/search:
    post:
      summary: Gets a list of `FeatureSet` matching the search criteria.
      description: >-
        `POST /featuresets/search` must accept a JSON version of

        `SearchFeatureSetsRequest` as the post body and will return a JSON
        version

        of `SearchFeatureSetsResponse`.
      operationId: SearchFeatureSets
      responses:
        '200':
          description: A successful response.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SearchFeatureSetsResponse'
      tags:
        - GA4GH
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SearchFeatureSetsRequest'
        required: true