openapi: 3.0.0
info:
  title: ga4gh/sequence_annotation_service.proto
  version: version not set
paths:
  /featuresets/{feature_set_id}:
    get:
      summary: Gets a `FeatureSet` by ID.
      description: '`GET /featuresets/{id}` will return a JSON version of `FeatureSet`.'
      operationId: GetFeatureSet
      responses:
        '200':
          description: A successful response.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/FeatureSet'
      parameters:
        - name: feature_set_id
          description: The ID of the `FeatureSet` to be retrieved.
          in: path
          required: true
          schema:
            type: string
      tags:
        - GA4GH