openapi: 3.0.0
info:
  title: ga4gh/sequence_annotation_service.proto
  version: version not set
paths:
  /features/{feature_id}:
    get:
      summary: Gets a `Feature` by ID.
      description: '`GET /features/{id}` will return a JSON version of `Feature`.'
      operationId: GetFeature
      responses:
        '200':
          description: A successful response.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Feature'
      parameters:
        - name: feature_id
          description: The ID of the `Feature` to be retrieved.
          in: path
          required: true
          schema:
            type: string
      tags:
        - GA4GH