openapi: 3.0.0
info:
  title: ga4gh/reference_service.proto
  version: version not set
paths:
  /referencesets/search:
    post:
      summary: Gets a list of `ReferenceSet` matching the search criteria.
      description: |-
        `POST /referencesets/search` must accept a JSON version of
        `SearchReferenceSetsRequest` as the post body and will return a JSON
        version of `SearchReferenceSetsResponse`.
      operationId: SearchReferenceSets
      responses:
        '200':
          description: A successful response.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SearchReferenceSetsResponse'
      tags:
        - GA4GH
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SearchReferenceSetsRequest'
        required: true