openapi: 3.0.0
info:
  title: ga4gh/allele_annotation_service.proto
  version: version not set
paths:
  /variantannotationsets/{variant_annotation_set_id}: 
    get:
      summary: Gets an `VariantAnnotationSet` by ID.
      description: >-
        `GET /variantannotationsets/{variant_annotation_set_id}` will return a JSON version of `VariantAnnotationSet`.
      operationId: GetVariantAnnotationSet
      responses:
        '200':
          description: A successful response.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/VariantAnnotationSet'
      parameters:
        - name: variant_annotation_set_id
          description: The ID of the `VariantAnnotationSet` to be retrieved.
          in: path
          required: true
          schema:
            type: string
      tags:
        - GA4GH