components:
  schemas:
    ContinuousSet:
      description: |-
        A set of Continous messages. Continuous values can be sent
        as a single Continuous message containing all values or a series
        of Continuous messages to either limit the size of the values array
        or to skip NaN values.
      properties:
        attributes:
          $ref: '#/components/schemas/Attributes'
        dataset_id:
          description: The ID of the dataset this annotation set belongs to.
          type: string
        id:
          description: The ID of this annotation set.
          type: string
        name:
          description: The display name for this annotation set.
          type: string
        reference_set_id:
          description: |-
            The ID of the reference set which defines the coordinate-space for this
            set of annotations.
          type: string
        source_uri:
          description: |-
            The source URI describing the file from which this annotation set was
            generated, if any.
          type: string
      type: object
info:
  title: BrAPI
  version: ''
openapi: 3.0.0
paths: {}
