components:
  schemas:
    Feature:
      description: |-
        Node in the annotation graph that annotates a contiguous region of a
        sequence.
      properties:
        attributes:
          $ref: '#/components/schemas/Attributes'
        child_ids:
          description: |-
            Ordered array of Child Ids of this node. Since not all child nodes are
            ordered by genomic coordinates, this can't always be reconstructed from
            parent_id's of the children alone.
          items:
            type: string
          type: array
        end:
          description: |-
            The end position (exclusive), resulting in [start, end) closed-open
            interval. This is typically calculated by `start +
            reference_bases.length`.
          format: int64
          type: string
        feature_set_id:
          description: Identifier for the containing feature set.
          type: string
        feature_type:
          $ref: '#/components/schemas/OntologyTerm'
        gene_symbol:
          description: |-
            The gene symbol the feature occurs on. This field may be
            replaced with a more generic representation in a future version.
          type: string
        id:
          description: Id of this annotation node.
          type: string
        name:
          description: An optional name to provide for the feature.
          type: string
        parent_id:
          description: Parent Id of this node. Set to empty string if node has no parent.
          type: string
        reference_name:
          description: The reference on which this feature occurs (e.g. `chr20` or `X`).
          type: string
        start:
          description: |-
            The start position at which this feature occurs (0-based). This
            corresponds to the first base of the string of reference bases. Genomic
            positions are non-negative integers less than reference length. Features
            spanning the join of circular genomes are represented as two features one
            on each side of the join (position 0).
          format: int64
          type: string
        strand:
          $ref: '#/components/schemas/Strand'
      type: object
info:
  title: BrAPI
  version: ''
openapi: 3.0.0
paths: {}
