components:
  schemas:
    SearchFeaturesRequest:
      description: This request maps to the body of `POST /features/search` as JSON.
      properties:
        end:
          description: |-
            Required, if name or symbol not provided.
            The end of the window (0-based, exclusive) for which overlapping
            features should be returned.
          format: int64
          type: string
        feature_set_id:
          description: |-
            The annotation set to search within. Either `feature_set_id` or
            `parent_id` must be non-empty.
          type: string
        feature_types:
          description: |-
            TODO: To be replaced with a fully featured ontology search
            once the Metadata definitions are rounded out.
            If specified, this query matches only annotations whose `feature_type`
            matches one of the provided ontology terms.
          items:
            type: string
          type: array
        gene_symbol:
          description: |-
            Only return features with matching the provided gene symbol
            (case-sensitive, exact match).
            This field may be replaced with a more generic representation
            in a future version.
          type: string
        name:
          description: Only returns features with this name (case-sensitive, exact match).
          type: string
        page_size:
          description: |-
            Specifies the maximum number of results to return in a single page.
            If unspecified, a system default will be used.
          format: int32
          type: integer
        page_token:
          description: |-
            The continuation token, which is used to page through large result sets.
            To get the next page of results, set this parameter to the value of
            `next_page_token` from the previous response.
          type: string
        parent_id:
          description: |-
            Restricts the search to direct children of the given parent `feature`
            ID. Either `feature_set_id` or `parent_id` must be non-empty.
          type: string
        reference_name:
          description: |-
            Only return features on the reference with this name
            (matched to literal reference name as imported from the GFF3).
          type: string
        start:
          description: |-
            Required, if name or symbol not provided.
            The beginning of the window (0-based, inclusive) for which
            overlapping features should be returned.  Genomic positions are
            non-negative integers less than reference length.  Requests spanning the
            join of circular genomes are represented as two requests one on each side
            of the join (position 0).
          format: int64
          type: string
      type: object
info:
  title: BrAPI
  version: ''
openapi: 3.0.0
paths: {}
