components:
  schemas:
    SearchContinuousRequest:
      description: This request maps to the body of `POST /continuous/search` as JSON.
      properties:
        continuous_set_id:
          description: The annotation set to search within. Required value.
          type: string
        end:
          description: "The end of the window (0-based, exclusive) for which continuous\nvalues should be returned. \nRequired value."
          format: int64
          type: string
        page_size:
          description: |-
            Specifies the maximum number of results to return in a single page.
            If unspecified, a system default will be used.
          format: int32
          type: integer
        page_token:
          description: |-
            The continuation token, which is used to page through large result sets.
            To get the next page of results, set this parameter to the value of
            `next_page_token` from the previous response.
          type: string
        reference_name:
          description: Get continuous values on this reference. Required value.
          type: string
        start:
          description: |-
            The beginning of the window (0-based, inclusive) for which
            continuous values should be returned.
            Required value.
          format: int64
          type: string
      type: object
info:
  title: BrAPI
  version: ''
openapi: 3.0.0
paths: {}
