components:
  schemas:
    SearchContinuousResponse:
      description: This is the response from `POST /continuous/search` expressed as JSON.
      properties:
        continuous:
          description: |-
            The list of matching continuous values, sorted by start position.
            All sampled values within the query range are returned.
            Unsampled values are assigned 'NaN' value. The values returned
            do not necessarily cover the same range as the query as all
            unsampled values might not be returned or if the query range extends
            beyond the reference range.
          items:
            $ref: '#/components/schemas/Continuous'
          type: array
        next_page_token:
          description: |-
            The continuation token, which is used to page through large result sets.
            Provide this value in a subsequent request to return the next page of
            results. This field will be empty if there aren't any additional results.
          type: string
      type: object
info:
  title: BrAPI
  version: ''
openapi: 3.0.0
paths: {}
