components:
  schemas:
    ExpressionUnit:
      default: EXPRESSION_UNIT_UNSPECIFIED
      enum:
      - EXPRESSION_UNIT_UNSPECIFIED
      - FPKM
      - TPM
      type: string
info:
  title: BrAPI
  version: ''
openapi: 3.0.0
paths: {}
