components:
  schemas:
    SearchRnaQuantificationSetsResponse:
      description: This is the response from 'POST /rnaquantificationsets/search' expressed as JSON.
      properties:
        next_page_token:
          description: |-
            The continuation token, which is used to page through large result sets.
            To get the next page of results, set this parameter to the value of
            'nextPageToken' from the previous response.
          type: string
        rna_quantification_sets:
          description: The list of matching quantification sets.
          items:
            $ref: '#/components/schemas/RnaQuantificationSet'
          type: array
      type: object
info:
  title: BrAPI
  version: ''
openapi: 3.0.0
paths: {}
