components:
  schemas:
    variantSetsSearchRequest: 
      description: |-
        ******************  /variantsets  *********************
        This request maps to the body of `POST /search/variantsets` as JSON.
      properties:
        studyDbIds: 
          description: The `Dataset` to search.
          type: array
          items:
            type: string
        variantSetDbIds: 
          description: The VariantSet to search.
          type: array
          items:
            type: string
        page:
          description: Which page of the "data" array to return. The page indexing starts at 0 (page=0 will return the first page). Default is 0.
          type: integer
        pageSize:
          description: The maximum number of items to return per page of the "data" array. Default is 1000.
          type: integer
      type: object
info:
  title: BrAPI
  version: ''
openapi: 3.0.0
paths: {}
