components:
  schemas:
    variantSetsSearchRequest: 
      description: |-
        ******************  /variantsets  *********************
        This request maps to the body of `POST /search/variantsets` as JSON.
      properties:
        studyDbIds: 
          description: The `Dataset` to search.
          type: array
          items:
            type: string
        variantSetDbIds: 
          description: The VariantSet to search.
          type: array
          items:
            type: string
        pageSize:
          description: |-
            Specifies the maximum number of results to return in a single page.
            If unspecified, a system default will be used.
          format: int32
          type: integer
        page: 
          description: |-
            Index number of the page to retrieve.
          format: int32
          type: integer
      type: object
info:
  title: BrAPI
  version: ''
openapi: 3.0.0
paths: {}
