components:
  schemas:
    variantSetsExtractRequest:
      description: |-
        This request maps to the body of `POST /variantsets/extract` as JSON.
      properties:
        callSetDbIds:
          description: The CallSet to search.
          type: array
          items:
            type: string
        page:
          description: Which page of the "data" array to return. The page indexing starts at 0 (page=0 will return the first page). Default is 0.
          type: integer
        pageSize:
          description: The maximum number of items to return per page of the "data" array. Default is 1000.
          type: integer
        variantDbIds: 
          description: The Variant to search.
          type: array
          items:
            type: string
        variantSetDbIds: 
          description: The VariantSet to search.
          type: array
          items:
            type: string
      type: object
info:
  title: BrAPI
  version: ''
openapi: 3.0.0
paths: {}
