components:
  schemas:
    Continuous:
      description: "This message defines a format for exchanging continuous valued signal data,\nsuch as those produced experimentally (e.g. ChIP-Seq data) or through \ncalculations (e.g. conservation scores). It can be used, for example,\nto share data from Wiggle, BigWig, and BedGraph sources."
      properties:
        continuous_set_id:
          description: Identifier for the containing continous set.
          type: string
        reference_name:
          description: The reference on which this signal is defined (e.g. `chr20` or `X`).
          type: string
        start:
          description: |-
            The start position at which this signal occurs (0-based). This
            corresponds to the first base of the string of reference bases. Genomic
            positions are non-negative integers less than the reference length.
          format: int64
          type: string
        values:
          description: The contiguous data values. Unsampled bases are given as NaN.
          items:
            format: double
            type: number
          type: array
      type: object
info:
  title: BrAPI
  version: ''
openapi: 3.0.0
paths: {}
