components:
  schemas:
    FeatureSet:
      description: A set of sequence features annotations.
      properties:
        attributes:
          $ref: '#/components/schemas/Attributes'
        dataset_id:
          description: The ID of the dataset this annotation set belongs to.
          type: string
        id:
          description: The ID of this annotation set.
          type: string
        name:
          description: The display name for this annotation set.
          type: string
        reference_set_id:
          description: |-
            The ID of the reference set which defines the coordinate-space for this
            set of annotations.
          type: string
        source_uri:
          description: |-
            The source URI describing the file from which this annotation set was
            generated, if any.
          type: string
      type: object
info:
  title: BrAPI
  version: ''
openapi: 3.0.0
paths: {}
