components:
  schemas:
    SearchFeatureSetsResponse:
      description: This is the response from `POST /featuresets/search` expressed as JSON.
      properties:
        feature_sets:
          description: The list of matching feature sets.
          items:
            $ref: '#/components/schemas/FeatureSet'
          type: array
        next_page_token:
          description: |-
            The continuation token, which is used to page through large result sets.
            Provide this value in a subsequent request to return the next page of
            results. This field will be empty if there aren't any additional results.
          type: string
      type: object
info:
  title: BrAPI
  version: ''
openapi: 3.0.0
paths: {}
