openapi: 3.0.0
info:
  title: ga4gh/genotype_phenotype_service.proto
  version: version not set
paths:
  /phenotypes/search:
    post:
      summary: >-
        Gets a list of phenotypes accessible through the API.

        `POST /phenotypes/search` must accept a JSON version of

        `SearchPhenotypesRequest` as the post body and will return a JSON
        version

        of `SearchPhenotypeAssociationSetsResponse`.
      operationId: SearchPhenotype
      responses:
        '200':
          description: A successful response.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SearchPhenotypesResponse'
      tags:
        - GA4GH
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SearchPhenotypesRequest'
        required: true