openapi: 3.0.0
info:
  title: ga4gh/rna_quantification_service.proto
  version: version not set
paths:
  /expressionlevels/{expression_level_id}:
    get:
      summary: |-
        Gets a `ExpressionLevel` by ID.
        `GET /expressionlevels/{id}` will return a JSON version of
        `ExpressionLevel`.
      operationId: GetExpressionLevel
      responses:
        '200':
          description: A successful response.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ExpressionLevel'
      parameters:
        - name: expression_level_id
          description: The ID of the `ExpressionLevel`.
          in: path
          required: true
          schema:
            type: string
      tags:
        - GA4GH