openapi: 3.0.0
info:
  title: ga4gh/rna_quantification_service.proto
  version: version not set
paths:
  /rnaquantifications/search:
    post:
      summary: >-
        Gets a list of 'RnaQuantification' matching the search criteria.

        'POST /rnaquantifications/search' must accept JSON version of

        'SearchRnaQuantificationsRequest' as the post body and will return a
        JSON

        version of 'SearchRnaQuantificationResponse'.
      operationId: SearchRnaQuantifications
      responses:
        '200':
          description: A successful response.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SearchRnaQuantificationsResponse'
      tags:
        - GA4GH
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SearchRnaQuantificationsRequest'
        required: true