openapi: 3.0.0
info:
  title: ga4gh/rna_quantification_service.proto
  version: version not set
paths:
  /rnaquantificationsets/search:
    post:
      summary: >-
        Gets a list of 'RnaQuantificationSet' matching the search criteria.

        'POST /rnaquantificationsets/search' must accept JSON version of

        'SearchRnaQuantificationSetRequest' as the post body and will return a
        JSON

        version of 'SearchRnaQuantificationSetResponse'.
      operationId: SearchRnaQuantificationSets
      responses:
        '200':
          description: A successful response.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SearchRnaQuantificationSetsResponse'
      tags:
        - GA4GH
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SearchRnaQuantificationSetsRequest'
        required: true