openapi: 3.0.0
info:
  title: ga4gh/rna_quantification_service.proto
  version: version not set
paths:
  /rnaquantificationsets/{rna_quantification_set_id}:
    get:
      summary: |-
        Gets a `RnaQuantificationSet` by ID.
        `GET /rnaquantificationsets/{id}` will return a JSON version of
        `RnaQuantificationSet`.
      operationId: GetRnaQuantificationSet
      responses:
        '200':
          description: A successful response.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RnaQuantificationSet'
      parameters:
        - name: rna_quantification_set_id
          description: The ID of the `RnaQuantificationSet`.
          in: path
          required: true
          schema:
            type: string
      tags:
        - GA4GH