openapi: 3.0.0
info:
  title: ga4gh/rna_quantification_service.proto
  version: version not set
paths:
  /rnaquantifications/{rna_quantification_id}:
    get:
      summary: |-
        Gets a `RnaQuantification` by ID.
        `GET /rnaquantifications/{id}` will return a JSON version of
        `RnaQuantification`.
      operationId: GetRnaQuantification
      responses:
        '200':
          description: A successful response.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RnaQuantification'
      parameters:
        - name: rna_quantification_id
          description: The ID of the `RnaQuantification`.
          in: path
          required: true
          schema:
            type: string
      tags:
        - GA4GH