info:
  title: BrAPI
  version: ''
openapi: 3.0.0
paths:
  /callsets:
    get:
      summary: Gets a filtered list of `CallSet` JSON objects.
      description: '
        Gets a filtered list of `CallSet` JSON objects.
      
        Also See:
        
        `GET /variantsets/{variantsetsDbId}/callsets`
        '
      operationId: GetCallSetCalls
      parameters:
        - name: callSetDbId
          description: The ID of the `CallSet` to be retrieved.
          in: query
          required: false
          schema:
            type: string
        - name: callSetName
          description: The human readbale name of the `CallSet` to be retrieved.
          in: query
          required: false
          schema:
            type: string
        - name: variantSetDbId
          description: The ID of the `VariantSet` to be retrieved.
          in: query
          required: false
          schema:
            type: string
        - $ref: '#/components/parameters/page'
        - $ref: '#/components/parameters/pageSize'
        - $ref: '#/components/parameters/authorizationHeader'
      responses:
        '200':
          description: A successful response.
          content:
            application/json:
              schema:
                properties:
                  metadata:
                    $ref: '#/components/schemas/metadata'
                  result:
                    properties:
                      data:
                        items:
                          $ref: '#/components/schemas/CallSets'
                        type: array
                    required:
                    - data
                    title: callSetsListResponseResult
                    type: object
                required:
                - metadata
                - result
                title: callSetsListResponse
                type: object
          headers: {}
        '400':
          $ref: '#/components/responses/400BadRequest'
        '401':
          $ref: '#/components/responses/401Unauthorized'
        '403':
          $ref: '#/components/responses/403Forbidden'
      tags:
        - Variants