info:
  title: BrAPI
  version: ''
openapi: 3.0.0
paths:
  /search/callsets/{searchResultsDbId}:
    post:
      summary: Gets a list of call sets matching the search criteria.
      description: >-
        `POST /callsets/search` must accept a JSON version of

        `SearchCallSetsRequest` as the post body and will return a JSON version
        of

        `SearchCallSetsResponse`.
      operationId: SearchCallSets
      parameters:
      - $ref: '#/components/parameters/searchResultsDbId'
      - $ref: '#/components/parameters/page'
      - $ref: '#/components/parameters/pageSize'
      - $ref: '#/components/parameters/authorizationHeader'
      responses:
        '200':
          description: A successful response.
          content:
            application/json:
              schema:
                properties:
                  metadata:
                    $ref: '#/components/schemas/metadata'
                  result:
                    properties:
                      data:
                        items:
                          $ref: '#/components/schemas/CallSet'
                        type: array
                    required:
                    - data
                    title: callSetListResponseResult
                    type: object
                required:
                - metadata
                - result
                title: callSetListResponse
                type: object
          headers: {}
        '400':
          $ref: '#/components/responses/400BadRequest'
        '401':
          $ref: '#/components/responses/401Unauthorized'
        '403':
          $ref: '#/components/responses/403Forbidden'
      tags:
        - Variants