info:
  title: BrAPI
  version: ''
openapi: 3.0.0
paths:
  /search/calls:
    post:
      summary: Submit a search request for `Calls`
      description: '`GET /callsets/{id}` will return a JSON version of `CallSet`.'
      operationId: GetCallSet
      parameters:
      - $ref: '#/components/parameters/authorizationHeader'
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/callsSearchRequest'
        description: Study Search request
      responses:
        '200':
          $ref: '#/components/responses/successfulSearchResponse'
        '400':
          $ref: '#/components/responses/400BadRequest'
        '401':
          $ref: '#/components/responses/401Unauthorized'
        '403':
          $ref: '#/components/responses/403Forbidden'
      tags:
      - Variants
      - Search Services