info:
  title: BrAPI
  version: ''
openapi: 3.0.0
paths:
  /search/variants:
    post:
      summary: Gets a list of `Variant` matching the search criteria.
      description: >-
        `POST /variants/search` must accept a JSON version of

        `SearchVariantsRequest` as the post body and will return a JSON version
        of

        `SearchVariantsResponse`.
      operationId: SearchVariants
      parameters:
      - $ref: '#/components/parameters/authorizationHeader'
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/variantsSearchRequest'
        description: Study Search request
      responses:
        '200':
          $ref: '#/components/responses/successfulSearchResponse'
        '400':
          $ref: '#/components/responses/400BadRequest'
        '401':
          $ref: '#/components/responses/401Unauthorized'
        '403':
          $ref: '#/components/responses/403Forbidden'
      tags:
      - Variants
      - Search Services