info:
  title: BrAPI
  version: ''
openapi: 3.0.0
paths:
  /variantsets:
    get:
      summary: Gets a filtered list of `VariantSets`.
      description: |-
        `GET /variantsets` will return a filtered list of `VariantSet`.
      operationId: GetVariantSet
      parameters:
        - name: variantSetDbId
          description: The ID of the `VariantSet` to be retrieved.
          in: query
          required: true
          schema:
            type: string
        - $ref: '#/components/parameters/page'
        - $ref: '#/components/parameters/pageSize'
        - $ref: '#/components/parameters/authorizationHeader'
      responses:
        '200':
          description: A successful response.
          content:
            application/json:
              schema:
                properties:
                  metadata:
                    $ref: '#/components/schemas/metadata'
                  result:
                    properties:
                      data:
                        items:
                          $ref: '#/components/schemas/VariantSet'
                        type: array
                    required:
                    - data
                    title: variantSetListResponseResult
                    type: object
                required:
                - metadata
                - result
                title: variantSetListResponse
                type: object
          headers: {}
        '400':
          $ref: '#/components/responses/400BadRequest'
        '401':
          $ref: '#/components/responses/401Unauthorized'
        '403':
          $ref: '#/components/responses/403Forbidden'
      tags:
        - Variants