components:
  schemas:
    Reference:
      description: |-
        A `Reference` is a canonical assembled contig, intended to act as a
        reference coordinate space for other genomic annotations. A single
        `Reference` might represent the human chromosome 1, for instance.

        `Reference` s are designed to be immutable.
      properties:
        attributes:
          $ref: '#/components/schemas/Attributes'
        id:
          description: The reference ID. Unique within the repository.
          type: string
        is_derived:
          description: |-
            A sequence X is said to be derived from source sequence Y, if X and Y
            are of the same length and the per-base sequence divergence at A/C/G/T
            bases
            is sufficiently small. Two sequences derived from the same official
            sequence share the same coordinates and annotations, and
            can be replaced with the official sequence for certain use cases.
          format: boolean
          type: boolean
        length:
          description: The length of this reference's sequence.
          format: int64
          type: string
        md5checksum:
          description: |-
            The MD5 checksum uniquely representing this `Reference` as a lower-case
            hexadecimal string, calculated as the MD5 of the upper-case sequence
            excluding all whitespace characters (this is equivalent to SQ:M5 in SAM).
          type: string
        name:
          description: The unique name of this reference within the Reference Set (e.g. '22').
          type: string
        source_accessions:
          description: |-
            All known corresponding accession IDs in INSDC (GenBank/ENA/DDBJ) which
            must include
            a version number, e.g. `GCF_000001405.26`.
          items:
            type: string
          type: array
        source_divergence:
          description: |-
            The `sourceDivergence` is the fraction of non-indel bases that do not match
            the
            reference this message was derived from.
          format: float
          type: number
        source_uri:
          description: |-
            The URI from which the sequence was obtained. Specifies a FASTA format
            file/string with one name, sequence pair. In most cases, clients should
            call
            the `getReferenceBases()` method to obtain sequence bases for a `Reference`
            instead of attempting to retrieve this URI.
          type: string
        species:
          $ref: '#/components/schemas/OntologyTerm'
      type: object
info:
  title: BrAPI
  version: ''
openapi: 3.0.0
paths: {}
