openapi: 3.0.0
info:
  title: ga4gh/bio_metadata_service.proto
  version: version not set
paths:
  /biosamples/search:
    post:
      summary: >-
        `POST /biosamples/search` must accept a JSON version of

        `SearchBiosamplesRequest` as the post body and will return a JSON
        version

        of `SearchBiosamplesResponse`.
      operationId: SearchBiosamples
      responses:
        '200':
          description: A successful response.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SearchBiosamplesResponse'
      tags:
        - GA4GH
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SearchBiosamplesRequest'
        required: true