openapi: 3.0.0
info:
  title: ga4gh/bio_metadata_service.proto
  version: version not set
paths:
  /individuals/{individual_id}:
    get:
      summary: |-
        Gets an `Individual` by ID.
        `GET /individuals/{id}` will return a JSON version of `Individual`.
      operationId: GetIndividual
      responses:
        '200':
          description: A successful response.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Individual'
      parameters:
        - name: individual_id
          description: The ID of the individual requested
          in: path
          required: true
          schema:
            type: string
      tags:
        - GA4GH