openapi: 3.0.0
info:
  title: ga4gh/bio_metadata_service.proto
  version: version not set
paths:
  /individuals/search:
    post:
      summary: >-
        Gets a list of Individuals accessible through the API.

        `POST /individuals/search` must accept a JSON version of

        `SearchIndividualsRequest` as the post body and will return a JSON
        version

        of `SearchIndividualsResponse`.
      operationId: SearchIndividuals
      responses:
        '200':
          description: A successful response.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SearchIndividualsResponse'
      tags:
        - GA4GH
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SearchIndividualsRequest'
        required: true