components:
  schemas:
    Attributes:
      properties:
        attr:
          additionalProperties:
            $ref: '#/components/schemas/AttributeValueList'
          type: object
      type: object
info:
  title: BrAPI
  version: ''
openapi: 3.0.0
paths: {}
