components:
  schemas:
    ExternalIdentifier:
      properties:
        database:
          description: The source of the identifier, e.g. `Ensembl`.
          type: string
        identifier:
          description: The ID defined by the external database, e.g. `ENST00000000000`.
          type: string
        version:
          description: The version of the object or the database, e.g. `78`.
          type: string
      title: Identifier from a public database
      type: object
info:
  title: BrAPI
  version: ''
openapi: 3.0.0
paths: {}
