openapi: 3.0.0
info:
  title: ga4gh/genotype_phenotype_service.proto
  version: version not set
paths:
  /phenotypeassociationsets/search:
    post:
      summary: >-
        Gets a list of association sets accessible through the API.

        `POST /phenotypeassociationsets/search` must accept a JSON version of

        `SearchPhenotypeAssociationSetsRequest` as the post body and will return
        a JSON version

        of `SearchPhenotypeAssociationSetsResponse`.
      operationId: SearchPhenotypeAssociationSets
      responses:
        '200':
          description: A successful response.
          content:
            application/json:
              schema:
                $ref: >-
                  #/components/schemas/SearchPhenotypeAssociationSetsResponse
      tags:
        - GA4GH
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SearchPhenotypeAssociationSetsRequest'
        required: true