openapi: 3.0.0
info:
  title: ga4gh/variant_service.proto
  version: version not set
paths:
  /callsets/search:
    post:
      summary: Gets a list of call sets matching the search criteria.
      description: >-
        `POST /callsets/search` must accept a JSON version of

        `SearchCallSetsRequest` as the post body and will return a JSON version
        of

        `SearchCallSetsResponse`.
      operationId: SearchCallSets
      responses:
        '200':
          description: A successful response.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SearchCallSetsResponse'
      tags:
        - GA4GH
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SearchCallSetsRequest'
        required: true