openapi: 3.0.0
info:
  title: ga4gh/variant_service.proto
  version: version not set
paths:
  /variants/{variant_id}:
    get:
      summary: Gets a `Variant` by ID.
      description: '`GET /variants/{id}` will return a JSON version of `Variant`.'
      operationId: GetVariant
      responses:
        '200':
          description: A successful response.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Variant'
      parameters:
        - name: variant_id
          description: The ID of the `Variant` to be retrieved.
          in: path
          required: true
          schema:
            type: string
      tags:
        - GA4GH