openapi: 3.0.0
info:
  title: ga4gh/variant_service.proto
  version: version not set
paths:
  /variantsets/search:
    post:
      summary: Gets a list of `VariantSet` matching the search criteria.
      description: >-
        `POST /variantsets/search` must accept a JSON version of

        `SearchVariantSetsRequest` as the post body and will return a JSON
        version

        of `SearchVariantSetsResponse`.
      operationId: SearchVariantSets
      responses:
        '200':
          description: A successful response.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SearchVariantSetsResponse'
      tags:
        - GA4GH
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SearchVariantSetsRequest'
        required: true