components:
  schemas:
    Age:
      properties:
        age:
          title: |-
            The :ref:`ISO 8601` age of this object as ISO8601
            duration or time intervals. The use of time intervals makes an additional
            anchor unnecessary (i.e. DOB and age can be represented as start-anchored
            time interval, e.g. 1967-11-21/P40Y10M05D)
            TODO: Anonymous reference time attribute/pointer?
          type: string
        age_class:
          $ref: '#/components/schemas/OntologyTerm'
      type: object
info:
  title: BrAPI
  version: ''
openapi: 3.0.0
paths: {}
