components:
  schemas:
    Biosample:
      properties:
        attributes:
          $ref: '#/components/schemas/Attributes'
        created:
          description: |-
            The :ref:`ISO 8601` time at which this Biosample record
            was created.
          type: string
        dataset_id:
          description: The ID of the dataset this Biosample belongs to.
          type: string
        description:
          description: |-
            The biosample's description. This attribute contains human readable text.
            The "description" attributes should not contain any structured data.
          type: string
        disease:
          $ref: '#/components/schemas/OntologyTerm'
        id:
          description: |-
            The Biosample :ref:`id `. This is unique in the
            context of the server instance.
          type: string
        individual_age_at_collection:
          $ref: '#/components/schemas/Age'
        individual_id:
          description: The individual this biosample was derived from.
          type: string
        name:
          description: The Biosample's name This is a label or symbolic identifier for the biosample.
          type: string
        updated:
          description: "The :ref:`ISO 8601` time at which this Biosample record was \nupdated."
          type: string
      type: object
info:
  title: BrAPI
  version: ''
openapi: 3.0.0
paths: {}
