openapi: 3.0.0
info:
  title: ga4gh/sequence_annotation_service.proto
  version: version not set
paths:
  /features/search:
    post:
      summary: Gets a list of `Feature` matching the search criteria.
      description: >-
        `POST /features/search` must accept a JSON version of

        `SearchFeaturesRequest` as the post body and will return a JSON version
        of

        `SearchFeaturesResponse`.
      operationId: SearchFeatures
      responses:
        '200':
          description: A successful response.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SearchFeaturesResponse'
      tags:
        - GA4GH
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SearchFeaturesRequest'
        required: true