components:
  schemas:
    Dataset:
      description: |-
        A Dataset is a collection of related data of multiple types.
        Data providers decide how to group data into datasets.
        See [Metadata API](../api/metadata.html) for a more detailed discussion.
      properties:
        attributes:
          $ref: '#/components/schemas/Attributes'
        description:
          description: Additional, human-readable information on the dataset.
          type: string
        id:
          description: The dataset's id, locally unique to the server instance.
          type: string
        name:
          description: The name of the dataset.
          type: string
      type: object
info:
  title: BrAPI
  version: ''
openapi: 3.0.0
paths: {}
